<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZgozugj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZgozugj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZgozugj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZgozugj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZgozugj\appDevDebugProjectContainer([
    'container.build_hash' => 'Zgozugj',
    'container.build_id' => '21acc41a',
    'container.build_time' => 1589440866,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZgozugj');
