<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNbxp6cd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNbxp6cd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNbxp6cd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNbxp6cd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNbxp6cd\appDevDebugProjectContainer([
    'container.build_hash' => 'Nbxp6cd',
    'container.build_id' => '3c53684a',
    'container.build_time' => 1588231791,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNbxp6cd');
